# Generated by Django 4.2.7 on 2023-11-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
    ]
