# Generated by Django 4.2.7 on 2023-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0003_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
