# Generated by Django 4.2.7 on 2023-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0004_alter_warehouse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
