import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import datetime


'''
The predictor class is meant to use the data generated by the data generator class and predict the heart rate of the individual.
It is a personalised LSTM for each individual.
It captures the unique features of the individual and predicts the heart rate.
'''
class HeartRatePredictor:
    def create_dataset():
        pass
    def create_model():
        pass
    def train_model():
        pass
    def save_model():
        pass
    def load_model():
        pass
    def predict():
        pass
        
    
    
    
    
    
'''
The analyse class is meant to analyse the data generated by the data generator class and predict the presence of any heart disease. 
It is a generalised LSTM+ Cluster for all individuals.
It captures the common features of the individuals and predicts the presence of heart disease.
'''   
class Analyser:
    def create_dataset():
        pass
    def create_model():
        pass
    def train_model():
        pass
    def save_model():
        pass
    def load_model():
        pass
    def analyse():
        pass